[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options



remappings = [
    "@openzeppelin=lib/openzeppelin-contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
scroll-sepolia = "${SCROLL_SEPOLIA_RPC_URL}"
scroll = "${SCROLL_RPC_URL}"

[etherscan]
scroll-sepolia-key = { key = "${ETHERSCAN_API_KEY}" }